# Generated by Django 5.0.7 on 2025-08-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_alter_reimbursementclaim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursementclaim',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Pending'), ('M', 'Manager Approved'), ('A', 'Approved'), ('R', 'Rejected')], default='D', max_length=3),
        ),
    ]
