# Generated by Django 5.0.7 on 2025-08-08 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_alter_reimbursementclaim_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reimbursementexpense',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='reimbursementexpense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reimbursementexpense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
