# Generated by Django 5.2.1 on 2025-08-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_alter_reimbursementexpense_options_and_more'),
    ]

    operations = [
    ]
