# Generated by Django 5.2.1 on 2025-08-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0006_auto_20250808_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursementexpense',
            name='receipt_drive_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
