# Generated by Django 5.2.1 on 2025-08-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0007_reimbursementexpense_receipt_drive_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursementexpense',
            name='receipt_filename',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
