# Generated by Django 5.0.7 on 2025-08-10 06:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0008_reimbursementexpense_receipt_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursementexpense',
            name='receipt_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reimbursementexpense',
            name='receipt_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursementexpense',
            name='receipt',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='receipt'),
        ),
    ]
