# Generated by Django 5.2.1 on 2025-06-29 15:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('video_call', 'Video Call'), ('site_visit', 'Site Visit'), ('documentation', 'Documentation'), ('complaint', 'Complaint'), ('follow_up', 'Follow Up'), ('advisory', 'Advisory'), ('other', 'Other')], default='call', max_length=20)),
                ('interaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duration in minutes (optional)', null=True)),
                ('notes', models.TextField(help_text='Detailed notes about the interaction')),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, help_text='Date for follow-up (if required)', null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='base.clientprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Interaction',
                'verbose_name_plural': 'Client Interactions',
                'ordering': ['-interaction_date', '-created_at'],
                'permissions': [('can_view_all_interactions', 'Can view all client interactions'), ('can_edit_own_interactions', 'Can edit own interactions')],
            },
        ),
    ]
