# Generated by Django 5.2.1 on 2025-05-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_lead_assigned_to_alter_lead_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentplanreview',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='investmentplanreview',
            name='review_date',
        ),
        migrations.AddField(
            model_name='investmentplanreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentplanreview',
            name='goal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentplanreview',
            name='monthly_investment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='investmentplanreview',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='investmentplanreview',
            name='tenure_years',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
