# Generated by Django 5.2.1 on 2025-06-30 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_clientinteraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('personal_details', 'Personal Details Modification'), ('account_creation', 'Account Creation'), ('account_closure', 'Account Closure Request'), ('adhoc_mf', 'Adhoc Requests - Mutual Fund'), ('adhoc_demat', 'Adhoc Requests - Demat'), ('report_request', 'Report Request')], max_length=20)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('required_documents', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('documents_requested', 'Documents Requested'), ('documents_received', 'Documents Received'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('client_verification', 'Client Verification'), ('closed', 'Closed'), ('on_hold', 'On Hold'), ('rejected', 'Rejected')], max_length=25)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('documents_requested', 'Documents Requested'), ('documents_received', 'Documents Received'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('client_verification', 'Client Verification'), ('closed', 'Closed'), ('on_hold', 'On Hold'), ('rejected', 'Rejected')], max_length=25)),
                ('transition_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-transition_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='additional_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='client_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='client_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='current_owner',
            field=models.ForeignKey(blank=True, help_text='Current person responsible for the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_service_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='documents_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='documents_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='documents_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='expected_completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='request_id',
            field=models.CharField(default=0, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='required_documents_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='resolution_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='sla_breached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('documents_requested', 'Documents Requested'), ('documents_received', 'Documents Received'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('client_verification', 'Client Verification'), ('closed', 'Closed'), ('on_hold', 'On Hold'), ('rejected', 'Rejected')], default='draft', max_length=25),
        ),
        migrations.CreateModel(
            name='ServiceRequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_internal', models.BooleanField(default=False)),
                ('commented_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='base.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='service_requests/documents/')),
                ('document_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='base.servicerequest')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='request_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='base.servicerequesttype'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', 'assigned_to'], name='base_servic_status_95bd29_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['client', 'status'], name='base_servic_client__469b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['raised_by', 'created_at'], name='base_servic_raised__df95f7_idx'),
        ),
        migrations.AddField(
            model_name='servicerequestworkflow',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_from_transitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequestworkflow',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='base.servicerequest'),
        ),
        migrations.AddField(
            model_name='servicerequestworkflow',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_to_transitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
