# Generated by Django 5.2.1 on 2025-06-11 14:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_businesstracker_user_investmentplanreview_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'permissions': [('can_convert_lead', 'Can convert lead to client'), ('can_reassign_lead', 'Can reassign lead to another RM')]},
        ),
        migrations.RemoveField(
            model_name='lead',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='lead',
            name='client_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_interaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='needs_reassignment_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_interaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='probability',
            field=models.PositiveIntegerField(default=0, help_text='Probability of conversion (0-100)%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='lead',
            name='reassignment_requested_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='reference_client',
            field=models.ForeignKey(blank=True, help_text='If source is Existing Client', limit_choices_to={'converted': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.lead'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'role__in': ['rm', 'rm_head', 'business_head']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('existing_client', 'Existing Client'), ('own_circle', 'Own Circle'), ('social_media', 'Social Media'), ('referral', 'Referral'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New Lead'), ('cold', 'Cold Lead'), ('warm', 'Warm Lead'), ('hot', 'Hot Lead'), ('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('conversion_requested', 'Conversion Requested'), ('converted', 'Converted to Client'), ('lost', 'Lost Lead')], default='new', max_length=50),
        ),
        migrations.CreateModel(
            name='LeadInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('call', 'Phone Call'), ('meeting', 'In-Person Meeting'), ('email', 'Email'), ('message', 'Message'), ('other', 'Other')], max_length=50)),
                ('interaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField()),
                ('next_step', models.TextField(blank=True, null=True)),
                ('next_date', models.DateField(blank=True, null=True)),
                ('interacted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='base.lead')),
            ],
            options={
                'verbose_name': 'Lead Interaction',
                'verbose_name_plural': 'Lead Interactions',
                'ordering': ['-interaction_date'],
            },
        ),
        migrations.CreateModel(
            name='LeadStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('old_status', models.CharField(max_length=255)),
                ('new_status', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('needs_approval', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_to_make', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_status_changes', to=settings.AUTH_USER_MODEL)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes_made', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='base.lead')),
            ],
            options={
                'verbose_name': 'Status Change',
                'verbose_name_plural': 'Status Changes',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('mf_sip', 'Mutual Fund SIP'), ('mf_lumpsum', 'Mutual Fund Lumpsum'), ('equity', 'Equity'), ('ai_portfolio', 'AI Portfolio'), ('loans', 'Loans'), ('insurance', 'Insurance'), ('pms', 'Portfolio Management Services'), ('aif', 'Alternative Investment Funds'), ('other', 'Other')], max_length=50)),
                ('interest_level', models.PositiveIntegerField(help_text='Interest level (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('discussed_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('discussed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_discussions', to='base.lead')),
            ],
            options={
                'verbose_name': 'Product Discussion',
                'verbose_name_plural': 'Product Discussions',
                'ordering': ['-discussed_on'],
            },
        ),
    ]
