# Generated by Django 5.2.1 on 2025-07-03 18:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_mutualfundscheme_executionplan_executionmetrics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('client_pan', models.CharField(blank=True, max_length=50)),
                ('scheme_name', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('warning', 'Warning')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Portfolio Upload Log',
                'verbose_name_plural': 'Portfolio Upload Logs',
                'ordering': ['upload', 'row_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='clientportfolio',
            options={'ordering': ['client_name', 'scheme_name'], 'verbose_name': 'Client Portfolio', 'verbose_name_plural': 'Client Portfolios'},
        ),
        migrations.RenameField(
            model_name='clientportfolio',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='clientportfolio',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='allocation_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Portfolio allocation %', max_digits=5),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='app_code',
            field=models.CharField(blank=True, help_text='Application code', max_length=50),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='arbitrage_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Arbitrage value', max_digits=15),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='client_iwell_code',
            field=models.CharField(blank=True, help_text='Client iWell code', max_length=50),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='client_name',
            field=models.CharField(default='Unknown Client', help_text='Client name from Excel', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='client_pan',
            field=models.CharField(db_index=True, default='UNKNOWN', help_text='Client PAN from Excel', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='client_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_holdings', to='base.clientprofile'),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='data_as_of_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when this data was valid'),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='debt_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Debt allocation value', max_digits=15),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='equity_code',
            field=models.CharField(blank=True, help_text='Equity code', max_length=50),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='equity_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Equity allocation value', max_digits=15),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='family_head',
            field=models.CharField(blank=True, help_text='Family head name', max_length=255),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='family_head_iwell_code',
            field=models.CharField(blank=True, help_text='Family head iWell code', max_length=50),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='hybrid_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hybrid allocation value', max_digits=15),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='is_mapped',
            field=models.BooleanField(default=False, help_text='Is mapped to a client profile'),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='isin_number',
            field=models.CharField(blank=True, help_text='ISIN number of the scheme', max_length=20),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='liquid_ultra_short_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Liquid & Ultra Short value', max_digits=15),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='mapped_ops',
            field=models.ForeignKey(blank=True, help_text='Mapped Operations person from User model', limit_choices_to={'role__in': ['ops_exec', 'ops_team_lead']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_ops_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='mapped_rm',
            field=models.ForeignKey(blank=True, help_text='Mapped RM from User model', limit_choices_to={'role': 'rm'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_rm_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='mapping_notes',
            field=models.TextField(blank=True, help_text='Notes about client mapping'),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='nav_date',
            field=models.DateField(blank=True, help_text='NAV date', null=True),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='nav_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='NAV price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='operations_code',
            field=models.CharField(blank=True, help_text='Operations code', max_length=50),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='operations_personnel',
            field=models.CharField(blank=True, help_text='Operations personnel', max_length=255),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='other_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Other category value', max_digits=15),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='relationship_manager',
            field=models.CharField(blank=True, help_text='Relationship manager name', max_length=255),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='rm_code',
            field=models.CharField(blank=True, help_text='RM code', max_length=50),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='scheme_name',
            field=models.CharField(default='UNKNOWN', help_text='Mutual fund scheme name', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='sub_broker',
            field=models.CharField(blank=True, help_text='Sub broker name', max_length=255),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='sub_broker_code',
            field=models.CharField(blank=True, help_text='Sub broker code', max_length=50),
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total holding value', max_digits=15),
        ),
        migrations.AddField(
            model_name='mutualfundscheme',
            name='isin_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mutualfundscheme',
            name='last_nav_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundscheme',
            name='last_nav_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundscheme',
            name='primary_asset_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mutualfundscheme',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientportfolio',
            name='cost_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost value of investment', max_digits=15),
        ),
        migrations.AlterField(
            model_name='clientportfolio',
            name='folio_number',
            field=models.CharField(blank=True, help_text='Folio number', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientportfolio',
            name='units',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Number of units held', max_digits=15),
        ),
        migrations.AlterField(
            model_name='mutualfundscheme',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mutualfundscheme',
            name='scheme_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='mutualfundscheme',
            name='scheme_type',
            field=models.CharField(choices=[('equity', 'Equity'), ('debt', 'Debt'), ('hybrid', 'Hybrid'), ('liquid', 'Liquid'), ('ultra_short', 'Ultra Short'), ('elss', 'ELSS'), ('index', 'Index'), ('etf', 'ETF'), ('arbitrage', 'Arbitrage'), ('other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='LegacyClientPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_number', models.CharField(blank=True, max_length=50)),
                ('units', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cost_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sip_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sip_date', models.PositiveIntegerField(blank=True, help_text='SIP date (1-28)', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_portfolio', to='base.client')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_holdings', to='base.mutualfundscheme')),
            ],
            options={
                'verbose_name': 'Legacy Client Portfolio',
                'verbose_name_plural': 'Legacy Client Portfolios',
                'ordering': ['client', 'scheme'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('file', models.FileField(upload_to='portfolio_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])])),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Processed')], default='pending', max_length=15)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('successful_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('processing_log', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('processing_summary', models.JSONField(blank=True, default=dict)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio Upload',
                'verbose_name_plural': 'Portfolio Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='clientportfolio',
            name='upload_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_entries', to='base.portfolioupload'),
        ),
        migrations.AddIndex(
            model_name='clientportfolio',
            index=models.Index(fields=['client_pan', 'scheme_name'], name='base_client_client__b05331_idx'),
        ),
        migrations.AddIndex(
            model_name='clientportfolio',
            index=models.Index(fields=['client_name'], name='base_client_client__b22ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='clientportfolio',
            index=models.Index(fields=['is_mapped', 'client_pan'], name='base_client_is_mapp_887139_idx'),
        ),
        migrations.AddIndex(
            model_name='clientportfolio',
            index=models.Index(fields=['upload_batch', 'is_mapped'], name='base_client_upload__eea1c5_idx'),
        ),
        migrations.AddField(
            model_name='portfoliouploadlog',
            name='portfolio_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_logs', to='base.clientportfolio'),
        ),
        migrations.AddField(
            model_name='portfoliouploadlog',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='base.portfolioupload'),
        ),
        migrations.RemoveField(
            model_name='clientportfolio',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientportfolio',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='clientportfolio',
            name='scheme',
        ),
        migrations.RemoveField(
            model_name='clientportfolio',
            name='sip_amount',
        ),
        migrations.RemoveField(
            model_name='clientportfolio',
            name='sip_date',
        ),
        migrations.AlterUniqueTogether(
            name='legacyclientportfolio',
            unique_together={('client', 'scheme', 'folio_number')},
        ),
    ]
