# Generated by Django 5.2.1 on 2025-06-18 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0005_alter_lead_options_remove_lead_contact_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='head',
            new_name='leader',
        ),
        migrations.RemoveField(
            model_name='user',
            name='managed_teams',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['rm', 'rm_head']}, related_name='team_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups managed by this RM Head', related_name='group_leaders', to='auth.group'),
        ),
    ]
