# Generated by Django 5.0.7 on 2025-07-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_portfoliouploadlog_alter_clientportfolio_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentplanreview',
            name='client',
        ),
        migrations.RemoveField(
            model_name='investmentplanreview',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='motilaldemataccount',
            name='client',
        ),
        migrations.RemoveField(
            model_name='prabhudasdemataccount',
            name='client',
        ),
        migrations.AlterModelOptions(
            name='portfoliouploadlog',
            options={'ordering': ['upload', 'row_number', 'created_at'], 'verbose_name': 'Portfolio Upload Log', 'verbose_name_plural': 'Portfolio Upload Logs'},
        ),
        migrations.AlterField(
            model_name='portfoliouploadlog',
            name='row_number',
            field=models.PositiveIntegerField(help_text='Row number in the uploaded file (0 for system messages)'),
        ),
        migrations.AddIndex(
            model_name='portfoliouploadlog',
            index=models.Index(fields=['upload', 'status'], name='base_portfo_upload__2413f5_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliouploadlog',
            index=models.Index(fields=['upload', 'row_number'], name='base_portfo_upload__674a36_idx'),
        ),
        migrations.DeleteModel(
            name='InvestmentPlanReview',
        ),
        migrations.DeleteModel(
            name='MotilalDematAccount',
        ),
        migrations.DeleteModel(
            name='PrabhudasDematAccount',
        ),
    ]
