# Generated by Django 5.0.7 on 2025-07-06 05:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_investmentplanreview_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequesttype',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Service Request Type', 'verbose_name_plural': 'Service Request Types'},
        ),
        migrations.AddField(
            model_name='servicerequesttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequesttype',
            name='default_priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='servicerequesttype',
            name='department',
            field=models.CharField(choices=[('operations', 'Operations'), ('compliance', 'Compliance'), ('relationship', 'Relationship Management')], default='operations', max_length=50),
        ),
        migrations.AddField(
            model_name='servicerequesttype',
            name='internal_instructions',
            field=models.TextField(blank=True, help_text='Processing instructions for operations team'),
        ),
        migrations.AddField(
            model_name='servicerequesttype',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Requires manager approval'),
        ),
        migrations.AddField(
            model_name='servicerequesttype',
            name='sla_hours',
            field=models.PositiveIntegerField(default=48, help_text='Standard SLA in hours'),
        ),
        migrations.AddField(
            model_name='servicerequesttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicerequesttype',
            name='category',
            field=models.CharField(choices=[('personal_details', 'Personal Details Modification'), ('account_creation', 'Account Creation'), ('account_closure', 'Account Closure Request'), ('adhoc_mf', 'Adhoc Requests - Mutual Fund'), ('adhoc_demat', 'Adhoc Requests - Demat'), ('report_request', 'Report Request'), ('general', 'General Request')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequesttype',
            name='required_documents',
            field=models.JSONField(blank=True, default=list, help_text='List of required document types'),
        ),
        migrations.AddIndex(
            model_name='servicerequesttype',
            index=models.Index(fields=['category', 'is_active'], name='base_servic_categor_294e57_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequesttype',
            index=models.Index(fields=['code'], name='base_servic_code_5c461e_idx'),
        ),
    ]
