# Generated by Django 5.0.7 on 2025-07-06 06:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_servicerequesttype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestIDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_key', models.DateField(help_text='Date for which this counter applies', unique=True)),
                ('current_value', models.PositiveIntegerField(default=0, help_text='Current counter value for this date')),
            ],
            options={
                'verbose_name': 'Service Request ID Counter',
                'verbose_name_plural': 'Service Request ID Counters',
            },
        ),
        migrations.AlterUniqueTogether(
            name='legacyclientportfolio',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='legacyclientportfolio',
            name='client',
        ),
        migrations.RemoveField(
            model_name='legacyclientportfolio',
            name='scheme',
        ),
        migrations.AlterModelOptions(
            name='executionplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Execution Plan', 'verbose_name_plural': 'Execution Plans'},
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service Request', 'verbose_name_plural': 'Service Requests'},
        ),
        migrations.AlterModelOptions(
            name='servicerequestcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service Request Comment', 'verbose_name_plural': 'Service Request Comments'},
        ),
        migrations.AlterModelOptions(
            name='servicerequestdocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Service Request Document', 'verbose_name_plural': 'Service Request Documents'},
        ),
        migrations.AlterModelOptions(
            name='servicerequestworkflow',
            options={'ordering': ['-transition_date'], 'verbose_name': 'Service Request Workflow', 'verbose_name_plural': 'Service Request Workflows'},
        ),
        migrations.RemoveIndex(
            model_name='portfoliouploadlog',
            name='base_portfo_upload__2413f5_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfoliouploadlog',
            name='base_portfo_upload__674a36_idx',
        ),
        migrations.AddField(
            model_name='servicerequestcomment',
            name='comment_type',
            field=models.CharField(choices=[('general', 'General Comment'), ('status_update', 'Status Update'), ('document_request', 'Document Request'), ('escalation', 'Escalation'), ('resolution', 'Resolution'), ('client_communication', 'Client Communication')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequestcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='base.servicerequestcomment'),
        ),
        migrations.AddField(
            model_name='servicerequestcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servicerequestdocument',
            name='document_type',
            field=models.CharField(blank=True, help_text="Type of document (e.g., 'identity_proof', 'bank_statement')", max_length=50),
        ),
        migrations.AddField(
            model_name='servicerequestdocument',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='servicerequestdocument',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequestdocument',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequestdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_service_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequestworkflow',
            name='auto_transition',
            field=models.BooleanField(default=False, help_text='Was this an automatic transition?'),
        ),
        migrations.AlterField(
            model_name='servicerequestcomment',
            name='commented_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicerequestcomment',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Internal ops comments vs client-facing'),
        ),
        migrations.AlterField(
            model_name='servicerequestdocument',
            name='document',
            field=models.FileField(upload_to='service_requests/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'xlsx', 'xls'])]),
        ),
        migrations.AlterField(
            model_name='servicerequestdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_service_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['request_id'], name='base_servic_request_729a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequestcomment',
            index=models.Index(fields=['service_request', 'created_at'], name='base_servic_service_1a5d27_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequestcomment',
            index=models.Index(fields=['commented_by', 'created_at'], name='base_servic_comment_302b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequestworkflow',
            index=models.Index(fields=['service_request', 'transition_date'], name='base_servic_service_cbc3ec_idx'),
        ),
        migrations.DeleteModel(
            name='LegacyClientPortfolio',
        ),
    ]
