# Generated by Django 5.2.1 on 2025-06-21 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_client_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_ops_team',
            field=models.BooleanField(default=False, help_text='Is this an operations team?'),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['rm_head', 'ops_team_lead']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('top_management', 'Top Management'), ('business_head', 'Business Head'), ('rm_head', 'RM Head'), ('rm', 'Relationship Manager'), ('ops_team_lead', 'Operations Team Lead'), ('ops_exec', 'Operations Executive')], max_length=20),
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_full_name', models.CharField(max_length=255)),
                ('family_head_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address_kyc', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('first_investment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('muted', 'Muted')], default='active', max_length=20)),
                ('muted_reason', models.TextField(blank=True, null=True)),
                ('muted_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_profiles', to=settings.AUTH_USER_MODEL)),
                ('mapped_ops_exec', models.ForeignKey(blank=True, limit_choices_to={'role': 'ops_exec'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_clients', to=settings.AUTH_USER_MODEL)),
                ('mapped_rm', models.ForeignKey(blank=True, limit_choices_to={'role': 'rm'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_clients', to=settings.AUTH_USER_MODEL)),
                ('muted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muted_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
                'ordering': ['client_full_name'],
                'permissions': [('can_mute_client', 'Can mute/unmute client'), ('can_change_pan', 'Can change PAN number'), ('can_change_name', 'Can change client name')],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='client_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_client', to='base.clientprofile'),
        ),
        migrations.AddField(
            model_name='lead',
            name='client_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_profile', to='base.clientprofile'),
        ),
        migrations.CreateModel(
            name='ClientProfileModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('modification_data', models.JSONField(help_text='Stores the changed fields and values')),
                ('reason', models.TextField()),
                ('requires_top_management', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_modifications', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='base.clientprofile')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_modifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Profile Modification',
                'verbose_name_plural': 'Client Profile Modifications',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='MFUCANAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('mfu', 'MFU CAN Account'), ('motilal', 'Motilal Demat'), ('prabhudas', 'Prabhudas Lilladher Demat')], max_length=20)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folio_number', models.CharField(max_length=50)),
                ('amc_name', models.CharField(max_length=100)),
                ('kyc_status', models.BooleanField(default=False)),
                ('last_transaction_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfu_accounts', to='base.clientprofile')),
            ],
            options={
                'verbose_name': 'MFU CAN Account',
                'verbose_name_plural': 'MFU CAN Accounts',
            },
        ),
        migrations.CreateModel(
            name='MotilalDematAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('mfu', 'MFU CAN Account'), ('motilal', 'Motilal Demat'), ('prabhudas', 'Prabhudas Lilladher Demat')], max_length=20)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker_name', models.CharField(max_length=100)),
                ('dp_id', models.CharField(max_length=20)),
                ('kyc_status', models.BooleanField(default=False)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('trading_enabled', models.BooleanField(default=False)),
                ('margin_enabled', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motilal_accounts', to='base.clientprofile')),
            ],
            options={
                'verbose_name': 'Motilal Demat Account',
                'verbose_name_plural': 'Motilal Demat Accounts',
            },
        ),
        migrations.CreateModel(
            name='PrabhudasDematAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('mfu', 'MFU CAN Account'), ('motilal', 'Motilal Demat'), ('prabhudas', 'Prabhudas Lilladher Demat')], max_length=20)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker_name', models.CharField(max_length=100)),
                ('dp_id', models.CharField(max_length=20)),
                ('kyc_status', models.BooleanField(default=False)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('commodity_enabled', models.BooleanField(default=False)),
                ('currency_enabled', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prabhudas_accounts', to='base.clientprofile')),
            ],
            options={
                'verbose_name': 'Prabhudas Demat Account',
                'verbose_name_plural': 'Prabhudas Demat Accounts',
            },
        ),
    ]
