# Generated by Django 5.2.1 on 2025-06-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_team_is_ops_team_alter_team_leader_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='client_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
