# Generated by Django 5.0.7 on 2025-07-06 09:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_client_options_remove_client_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Management Company',
                'verbose_name_plural': 'Asset Management Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchemeUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(help_text='Row number in the uploaded file (0 for system messages)')),
                ('amc_name', models.CharField(blank=True, max_length=255)),
                ('scheme_name', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('warning', 'Warning')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Scheme Upload Log',
                'verbose_name_plural': 'Scheme Upload Logs',
                'ordering': ['upload', 'row_number', 'created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='mutualfundscheme',
            name='isin_number',
        ),
        migrations.RemoveField(
            model_name='mutualfundscheme',
            name='primary_asset_class',
        ),
        migrations.AddField(
            model_name='mutualfundscheme',
            name='category',
            field=models.CharField(blank=True, help_text='Category as per AMFI classification', max_length=100),
        ),
        migrations.AddField(
            model_name='mutualfundscheme',
            name='isin_div_reinvestment',
            field=models.CharField(blank=True, help_text='ISIN for Dividend Reinvestment option', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mutualfundscheme',
            name='isin_growth',
            field=models.CharField(blank=True, help_text='ISIN for Growth/Div Payout option', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mutualfundscheme',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mutualfundscheme',
            name='amc_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mutualfundscheme',
            name='scheme_name',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='SchemeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], default='moderate', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='base.schemecategory')),
            ],
            options={
                'verbose_name': 'Scheme Category',
                'verbose_name_plural': 'Scheme Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchemeUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('file', models.FileField(upload_to='scheme_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])])),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Processed')], default='pending', max_length=15)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('successful_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('updated_rows', models.PositiveIntegerField(default=0)),
                ('processing_log', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('processing_summary', models.JSONField(blank=True, default=dict)),
                ('update_existing', models.BooleanField(default=True, help_text='Update existing schemes if found')),
                ('mark_missing_inactive', models.BooleanField(default=False, help_text='Mark schemes not in upload as inactive')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheme Upload',
                'verbose_name_plural': 'Scheme Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='mutualfundscheme',
            name='upload_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_schemes', to='base.schemeupload'),
        ),
        migrations.AddIndex(
            model_name='mutualfundscheme',
            index=models.Index(fields=['amc_name', 'scheme_name'], name='base_mutual_amc_nam_a68155_idx'),
        ),
        migrations.AddIndex(
            model_name='mutualfundscheme',
            index=models.Index(fields=['scheme_code'], name='base_mutual_scheme__794750_idx'),
        ),
        migrations.AddIndex(
            model_name='mutualfundscheme',
            index=models.Index(fields=['isin_growth'], name='base_mutual_isin_gr_34f5f2_idx'),
        ),
        migrations.AddIndex(
            model_name='mutualfundscheme',
            index=models.Index(fields=['category', 'scheme_type'], name='base_mutual_categor_3aa737_idx'),
        ),
        migrations.AddIndex(
            model_name='mutualfundscheme',
            index=models.Index(fields=['is_active'], name='base_mutual_is_acti_8081cc_idx'),
        ),
        migrations.AddField(
            model_name='schemeuploadlog',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_logs', to='base.mutualfundscheme'),
        ),
        migrations.AddField(
            model_name='schemeuploadlog',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='base.schemeupload'),
        ),
    ]
