# Generated by Django 5.0.7 on 2025-07-06 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_amc_schemeuploadlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeupload',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schemeupload',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schemeupload',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Mark as archived instead of deleting'),
        ),
        migrations.AlterField(
            model_name='schemeupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Processed'), ('archived', 'Archived')], default='pending', max_length=15),
        ),
    ]
