# Generated by Django 5.0.7 on 2025-07-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_schemeupload_archived_at_schemeupload_archived_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AMC',
        ),
        migrations.DeleteModel(
            name='SchemeCategory',
        ),
    ]
