# Generated by Django 5.0.7 on 2025-07-07 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_delete_amc_delete_schemecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionplan',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executionplan',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_execution_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
