# Generated by Django 5.0.7 on 2025-07-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_clientupload_clientuploadlog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clientuploadlog',
            index=models.Index(fields=['upload', 'status'], name='base_client_upload__a67a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='clientuploadlog',
            index=models.Index(fields=['upload', 'row_number'], name='base_client_upload__9a5687_idx'),
        ),
    ]
