# Generated by Django 5.2.1 on 2025-07-31 04:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_clientuploadlog_base_client_upload__a67a4c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientportfolio',
            name='client_name',
            field=models.CharField(db_index=True, help_text='Client name from Excel', max_length=255),
        ),
        migrations.AlterField(
            model_name='clientportfolio',
            name='scheme_name',
            field=models.CharField(db_index=True, help_text='Mutual fund scheme name', max_length=300),
        ),
        migrations.AlterField(
            model_name='portfoliouploadlog',
            name='client_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='portfoliouploadlog',
            name='client_pan',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='portfoliouploadlog',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='portfoliouploadlog',
            name='row_number',
            field=models.PositiveIntegerField(db_index=True, help_text='Row number in the uploaded file (0 for system messages)'),
        ),
        migrations.AlterField(
            model_name='portfoliouploadlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('warning', 'Warning')], db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='clientportfolio',
            index=models.Index(fields=['client_pan', 'is_mapped'], name='base_client_client__cd1bd8_idx'),
        ),
        migrations.AddIndex(
            model_name='clientportfolio',
            index=models.Index(fields=['upload_batch', 'created_at'], name='base_client_upload__da1f86_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliouploadlog',
            index=models.Index(fields=['upload', 'status'], name='base_portfo_upload__2413f5_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliouploadlog',
            index=models.Index(fields=['upload', 'row_number'], name='base_portfo_upload__674a36_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliouploadlog',
            index=models.Index(fields=['upload', 'created_at'], name='base_portfo_upload__49e29a_idx'),
        ),
    ]
