# Generated by Django 5.0.7 on 2025-08-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_clientportfolio_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeupload',
            name='duplicate_isins_found',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schemeupload',
            name='empty_categories_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schemeupload',
            name='empty_isins_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schemeupload',
            name='skip_empty_categories',
            field=models.BooleanField(default=False, help_text='Skip schemes with empty categories'),
        ),
    ]
