# Generated by Django 5.0.7 on 2025-08-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_schemeupload_duplicate_isins_found_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualfundscheme',
            name='scheme_code',
            field=models.CharField(max_length=50),
        ),
    ]
