# Generated by Django 5.2.1 on 2025-08-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_mutualfundscheme_scheme_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequesttype',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
