# Generated by Django 5.2.1 on 2025-08-02 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_servicerequesttype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='business_verification_notes',
            field=models.TextField(blank=True, help_text='Business verification notes from conversion approval'),
        ),
        migrations.AddField(
            model_name='client',
            name='conversion_approved_by',
            field=models.ForeignKey(blank=True, help_text='Ops team lead who approved the conversion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_conversions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='converted_from_lead',
            field=models.ForeignKey(blank=True, help_text='The lead that was converted to create this client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_client', to='base.lead'),
        ),
        migrations.AddField(
            model_name='client',
            name='original_rm',
            field=models.ForeignKey(blank=True, help_text='Original RM who handled the lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_rm_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='business_verification_notes',
            field=models.TextField(blank=True, help_text='Business verification notes from ops team lead'),
        ),
        migrations.AddField(
            model_name='lead',
            name='business_verified_by',
            field=models.ForeignKey(blank=True, help_text='Ops team lead who verified business details', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_verified_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='conversion_requested_at',
            field=models.DateTimeField(blank=True, help_text='When conversion was requested', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='conversion_requested_by',
            field=models.ForeignKey(blank=True, help_text='RM who requested the conversion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_conversions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='final_assigned_rm',
            field=models.ForeignKey(blank=True, help_text='RM assigned to the client after conversion (can be different from original RM)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_assigned_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='generated_client',
            field=models.OneToOneField(blank=True, help_text='The client record generated from this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='base.client'),
        ),
    ]
