# Generated by Django 5.2.1 on 2025-08-03 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_client_business_verification_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planaction',
            name='action_mode',
            field=models.CharField(choices=[('portfolio', 'Portfolio Action'), ('new_investment', 'New Investment')], default='new_investment', help_text='Whether this action is on existing portfolio or new investment', max_length=20),
        ),
        migrations.AddField(
            model_name='planaction',
            name='frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly')], help_text='Frequency for SIP/STP/SWP', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='planaction',
            name='portfolio_folio_number',
            field=models.CharField(blank=True, help_text='Folio number from portfolio holding', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planaction',
            name='portfolio_holding_id',
            field=models.PositiveIntegerField(blank=True, help_text='Reference to ClientPortfolio holding ID', null=True),
        ),
        migrations.AddField(
            model_name='planaction',
            name='portfolio_isin',
            field=models.CharField(blank=True, help_text='ISIN from portfolio holding', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='planaction',
            name='portfolio_scheme_name',
            field=models.CharField(blank=True, help_text='Scheme name from client portfolio (for portfolio-based actions)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='planaction',
            name='scheme',
            field=models.ForeignKey(blank=True, help_text='Mutual Fund Scheme (for new investments only)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_actions', to='base.mutualfundscheme'),
        ),
        migrations.AlterField(
            model_name='planaction',
            name='target_scheme',
            field=models.ForeignKey(blank=True, help_text='Target scheme for switch/STP (always from MutualFundScheme)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_actions', to='base.mutualfundscheme'),
        ),
        migrations.AddIndex(
            model_name='planaction',
            index=models.Index(fields=['execution_plan', 'status'], name='base_planac_executi_40a871_idx'),
        ),
        migrations.AddIndex(
            model_name='planaction',
            index=models.Index(fields=['action_mode', 'action_type'], name='base_planac_action__96f173_idx'),
        ),
        migrations.AddIndex(
            model_name='planaction',
            index=models.Index(fields=['portfolio_holding_id'], name='base_planac_portfol_1c7920_idx'),
        ),
    ]
