# Generated by Django 5.2.1 on 2025-08-03 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_planaction_action_mode_planaction_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioActionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_holding_id', models.PositiveIntegerField(help_text='Reference to ClientPortfolio ID')),
                ('original_scheme_name', models.CharField(help_text='Original scheme name from portfolio', max_length=500)),
                ('original_isin', models.CharField(blank=True, help_text='Original ISIN from portfolio', max_length=50)),
                ('original_folio_number', models.CharField(blank=True, help_text='Original folio number from portfolio', max_length=100)),
                ('original_units', models.DecimalField(blank=True, decimal_places=4, help_text='Original units in portfolio at time of action creation', max_digits=15, null=True)),
                ('original_value', models.DecimalField(blank=True, decimal_places=2, help_text='Original value in portfolio at time of action creation', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_mapping', to='base.planaction')),
            ],
            options={
                'verbose_name': 'Portfolio Action Mapping',
                'verbose_name_plural': 'Portfolio Action Mappings',
                'indexes': [models.Index(fields=['portfolio_holding_id'], name='base_portfo_portfol_48cc4b_idx'), models.Index(fields=['original_scheme_name'], name='base_portfo_origina_280367_idx')],
            },
        ),
    ]
