# Generated by Django 5.2.1 on 2025-08-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_portfolioactionmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='pan_number',
            field=models.CharField(default='NA', help_text="PAN number or 'NA' if not available", max_length=10),
        ),
    ]
