# Generated by Django 5.2.1 on 2025-08-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_clientprofile_pan_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='pan_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
