# Generated by Django 5.0.7 on 2025-09-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_clientprofile_pan_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('email__gt', ''), ('email__isnull', False)), models.Q(('mobile__gt', ''), ('mobile__isnull', False)), _connector='OR'), name='lead_contact_method_required', violation_error_message='At least one contact method (email or mobile) is required.'),
        ),
    ]
